resources:
- ../base
- env-ops-configmap.yaml
- r619aa47/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r619aa47/revision-patch.yaml
  target:
    kind: Service
- path: r619aa47/routing-patch.yaml
  target:
    kind: Service