resources:
- ../base
- env-ops-configmap.yaml
- r798e9c3/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r798e9c3/revision-patch.yaml
  target:
    kind: Service
- path: r798e9c3/routing-patch.yaml
  target:
    kind: Service