resources:
- ../base
- env-ops-configmap.yaml
- r03533bc/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r03533bc/revision-patch.yaml
  target:
    kind: Service
- path: r03533bc/routing-patch.yaml
  target:
    kind: Service