resources:
- ../base
- env-ops-configmap.yaml
- re2305bc/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: re2305bc/revision-patch.yaml
  target:
    kind: Service
- path: re2305bc/routing-patch.yaml
  target:
    kind: Service