resources:
- ../base
- env-ops-configmap.yaml
- r1981e7a/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r1981e7a/revision-patch.yaml
  target:
    kind: Service
- path: r1981e7a/routing-patch.yaml
  target:
    kind: Service