resources:
- ../base
- env-ops-configmap.yaml
- rdf5fdb2/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: rdf5fdb2/revision-patch.yaml
  target:
    kind: Service
- path: rdf5fdb2/routing-patch.yaml
  target:
    kind: Service