resources:
- ../base
- env-ops-configmap.yaml
- r8bd86d8/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r8bd86d8/revision-patch.yaml
  target:
    kind: Service
- path: r8bd86d8/routing-patch.yaml
  target:
    kind: Service