resources:
- ../base
- env-ops-configmap.yaml
- rff1e800/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: rff1e800/revision-patch.yaml
  target:
    kind: Service
- path: rff1e800/routing-patch.yaml
  target:
    kind: Service